=== honey-srini/xml/xml/test.dtd
<!ELEMENT Mydevices (device+)>
<!ELEMENT device (name,brand,model)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT brand (#PCDATA)>
<!ELEMENT model (#PCDATA)>

=== honey-srini/xml/xml/test.xml
<!DOCTYPE Mydevices SYSTEM "test.dtd">
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<Mydevices>
    <device>
        <name>laptop</name>
        <brand>lenovo</brand>
        <model>thinkpad</model>
    </device>

    <device>
        <name>phone</name>
        <brand>redmi</brand>
        <model>k20 pro</model>
    </device>

    <device>
        <name>phone</name>
        <brand>apple</brand>
        <model>iphone x</model>
    </device>

</Mydevices>
